---
- name: Configure MongoDB
  hosts: db
  tags: db-tag
  become: true # Выполняем от root
  vars:
    mongo_bind_ip: 0.0.0.0 # Переменная которая будет пременена в шаблоне Jinja
  tasks:
    - name: Change mongo config file
      ansible.builtin.template:
        src: templates/mongod.conf.j2 # <-- Путь до локального файла-шаблона
        dest: /etc/mongod.conf # <-- Путь на удаленном хосте к файлу конфигурации который будет заменен шаблоном
        mode: 0644 # <-- Права на файл, которые нужно установить
      notify: restart mongod # запустит handlers "restart mongod" если конфигурация изменится
       
  handlers: # <-- Добавим блок handlers и задачу для рестарта mongodb
    - name: restart mongod
      service: name=mongod state=restarted

- name: Configure App
  hosts: app
  tags: app-tag
  become: true
  vars:
    db_host: 10.132.0.20 # <-- Внутренний IP адрес нашего хоста с базой данных
  tasks:
    - name: Add unit file for Puma # Копируем puma service в systemd и перезапускаем service
      ansible.builtin.copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma # запустит handlers "reload puma" если конфигурация изменится

    - name: Add config for DB connection # добавляем переменную DATABASE_URL (ip адрес базы) в db_config для подключения к базе 
      ansible.builtin.template:
        src: templates/db_config.j2
        dest: /home/baggurd/db_config
        owner: baggurd
        group: baggurd

    - name: enable puma # Включаем Puma Service
      systemd: name=puma enabled=yes

  handlers:
    - name: reload puma # Перезагружаем Puma Service
      systemd: name=puma state=restarted

- name: Deploy App
  hosts: app
  tags: deploy-tag
  become: true
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/baggurd/reddit
        version: monolith # <-- Указываем нужную ветку
      notify: restart puma

    - name: Bundle install # Управление зависимостями для ruby
      community.general.bundler:
        state: present
        chdir: /home/baggurd/reddit # <-- В какой директории выполнить команду bundle

  handlers:
    - name: restart puma # Перезагружаем Puma Service
      systemd: name=puma state=restarted
