---
- name: Install Python
  ansible.builtin.import_playbook: python.yml
- name: Database MongoDB Install
  ansible.builtin.import_playbook: db.yml
- name: Application Install
  ansible.builtin.import_playbook: app.yml
- name: Deploy Application
  ansible.builtin.import_playbook: deploy.yml
#- name: Add users from credentials.yml file
#  ansible.builtin.import_playbook: users.yml
  