---
# tasks file for app
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"

- name: Install Ruby
  ansible.builtin.include_tasks:
    file: ruby.yml
  tags: ruby
- name: Install Puma
  ansible.builtin.include_tasks:
    file: puma.yml
