---
- name: Add unit file for Puma # Копируем puma service в systemd и перезапускаем service
  ansible.builtin.template:
    src: puma.service.j2 # Достаточно указать имя а не полный путь
    dest: /etc/systemd/system/puma.service
    mode: 0644
  notify: Reload puma # запустит handlers "reload puma" если конфигурация изменится

# - name: Create user
#   ansible.builtin.user:
#     name: "baggurd"
#     groups: "sudo"

- name: Add config for DB connection # добавляем переменную DATABASE_URL (ip адрес базы) в db_config для подключения к базе
  ansible.builtin.template:
    src: db_config.j2 # Достаточно указать имя а не полный путь
    dest: /home/{{ deploy_user }}/db_config
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: 0644

- name: Enable puma # Включаем Puma Service
  ansible.builtin.systemd:
    name: puma
    enabled: true
