---
- name: Clone
  hosts: app
  tasks:
    - name: Clone Repository
      ansible.builtin.git: # Клонируем Репозиторий
        repo: https://github.com/express42/reddit.git
        dest: /home/baggurd/reddit
