---
- name: Configure hosts & deploy application
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0 # Переменная которая будет пременена в шаблоне Jinja
    db_host: 10.132.0.19 # <-- Внутренний IP адрес нашего хоста с базой данных
  tasks:
    - name: Change mongo config file
      become: true # <-- Выполнить задание от root
      ansible.builtin.template:
        src: templates/mongod.conf.j2 # <-- Путь до локального файла-шаблона
        dest: /etc/mongod.conf # <-- Путь на удаленном хосте к файлу конфигурации который будет заменен шаблоном
        mode: 0644 # <-- Права на файл, которые нужно установить
      tags: db-tag # <-- Список тэгов для задачи
      notify: restart mongod # запустит handlers "restart mongod" если конфигурация изменится

    - name: Add unit file for Puma # Копируем puma service в systemd и перезапускаем service
      become: true
      ansible.builtin.copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      tags: app-tag
      notify: reload puma # запустит handlers "reload puma" если конфигурация изменится

    - name: Add config for DB connection # добавляем переменную DATABASE_URL (ip адрес базы) в db_config для подключения к базе 
      ansible.builtin.template:
        src: templates/db_config.j2
        dest: /home/baggurd/db_config
      tags: app-tag

    - name: enable puma
      become: true
      systemd: name=puma enabled=yes
      tags: app-tag

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/baggurd/reddit
        version: monolith # <-- Указываем нужную ветку
      tags: deploy-tag
      notify: reload puma

    - name: Bundle install # Управление зависимостями для ruby
      community.general.bundler:
        state: present
        chdir: /home/baggurd/reddit # <-- В какой директории выполнить команду bundle
      tags: deploy-tag

  handlers: # <-- Добавим блок handlers и задачу для рестарта mongodb
    - name: restart mongod
      become: true
      service: name=mongod state=restarted
      
    - name: reload puma
      become: true
      systemd: name=puma state=restarted
